name: Update list

on: 
  push:
    branches: [main]
    paths: 
      - '.github/workflows/list.yml'
  schedule:
    - cron: '0 */2 * * *'

jobs:
  update_resources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name:  install jq & set time & tree
        shell: bash
        run: |
          sudo apt install jq
          jq --version
          sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: check update
        id: check_updata
        shell: bash
        run: |
          echo '========================== 检查区 ==========================='
          wget --no-dns-cache --random-wait --continue -d -T 60 -t 30 --header='authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --no-warc-digests -O latest.txt "https://api.github.com/repos/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest"
          if md5sum -c --quiet 'md5.md5'; then
            # No changes
            echo 'changed=false' >> $GITHUB_OUTPUT
          else
            # Changes detected
            echo 'changed=true' >> $GITHUB_OUTPUT
            md5sum latest.txt > md5.md5
          fi
          echo '============================================================'
      - name: Fetch list
        if: steps.check_updata.outputs.changed == 'true'
        shell: bash
        run: |
          # 获取 Latest GitHub Releases 名称 & 资源地址
          name=$(cat "latest.txt" | jq -r ".name")
          cat "latest.txt" | jq -r ".zipball_url" > d.txt
          # 获取的 target_commitish  前1-7个字符
          targetcommitish=$(cut "latest.txt" -c1-7 | jq -r ".target_commitish")
          # 下载资源
          wget --no-dns-cache --random-wait --continue -d -T 60 -t 30 -O latest.zip -i "d.txt"
          # 解压
          unzip -q latest.zip
          ls
          # 跳转
          cd ./CFPAOrg-Minecraft-Mod-Language-Package-${targetcommitish}
          cd ./projects
          ######################################################
          ###################### 1.12.2
          cd ./1.12.2
          cd ./assets
          tree -t -h -N -D -H 1.12.2 > 1.12.2.html
          mv *.html ../
          cd ../
          mv *.html ../
          cd ../
          ###################### 1.16
          cd ./1.16
          cd ./assets
          tree -t -h -N -D -H 1.16-${name} > 1.16.html
          mv *.html ../
          cd ../
          mv *.html ../
          cd ../
          ###################### 1.16-fabric
          cd ./1.16-fabric
          cd ./assets
          tree -t -h -N -D -H 1.16-fabric-${name} > 1.16-fabric.html
          mv *.html ../
          cd ../
          mv *.html ../
          cd ../
          ###################### 1.18
          cd ./1.18
          cd ./assets
          tree -t -h -N -D -H 1.18-${name} > 1.18.html
          mv *.html ../
          cd ../
          mv *.html ../
          cd ../
          ###################### 1.18-fabric
          cd ./1.18-fabric
          cd ./assets
          tree -t -h -N -D -H 1.18-fabric-${name} > 1.18-fabric.html
          mv *.html ../
          cd ../
          mv *.html ../
          cd ../
          ###################### 1.19
          cd ./1.19
          cd ./assets
          tree -t -h -N -D -H 1.19-${name} > 1.19.html
          mv *.html ../
          cd ../
          mv *.html ../
          cd ../
          ######################################################
          # 文件传到上上一层
          mv *.html ../
          cd ../
          mv *.html ../
          cd ../
          # 删除文件
          rm -r ./CFPAOrg-Minecraft-Mod-Language-Package-${target_commitish}
          rm latest.zip
          # commit
          git add -A
          git commit -m "${name}(`date '+%Y-%m-%d %H:%M:%S'`)$GITHUB_RUN_ID
          
          GitHub Action: https://github.com/${{ github.repository }}/actions/runs/$GITHUB_RUN_ID
            "
      - name: Push changes
        if: steps.check_updata.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}