name: Update list

on: 
  push:
    branches: [main]
    paths: 
      - '.github/workflows/list.yml'
      - 'l.sh'
  schedule:
    - cron: '0 */2 * * *'

jobs:
  update_list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name:  install jq & set time & tree
        shell: bash
        run: |
          sudo apt install jq
          jq --version
          sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: check update
        id: check_updata
        shell: bash
        run: |
          echo '========================== 检查区 ==========================='
          wget --no-dns-cache --random-wait --continue -d -T 60 -t 30 --no-warc-digests -O latest.txt "https://api.github.com/repos/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest"
          if md5sum -c --quiet 'md5.md5'; then
            # No changes
            echo 'changed=false' >> $GITHUB_OUTPUT
          else
            # Changes detected
            echo 'changed=true' >> $GITHUB_OUTPUT
            md5sum latest.txt > md5.md5
          fi
          echo '============================================================'
      - name: Fetch list
        if: steps.check_updata.outputs.changed == 'true'
        shell: bash
        run: |
          ./l.sh
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "${name}(`date '+%Y-%m-%d %H:%M:%S'`)$GITHUB_RUN_ID
          
          GitHub Action: https://github.com/${{ github.repository }}/actions/runs/$GITHUB_RUN_ID
            "
      - name: Push changes
        if: steps.check_updata.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}